-- Restore the tables used by first-party Google/GitHub login.
-- Safe to run more than once in the Supabase SQL editor.
-- The backend must use a service_role key; never expose that key to the browser.

begin;

create table if not exists public.awsl_users (
    id bigint generated by default as identity primary key,
    user_name text not null,
    user_email text not null unique,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    password text not null,
    active boolean not null default true,
    role text not null default 'user'
);

alter table public.awsl_users
    add column if not exists active boolean not null default true,
    add column if not exists role text not null default 'user';

create index if not exists awsl_users_email_index
    on public.awsl_users (lower(user_email));

create table if not exists public.awsl_oauth_users (
    id bigint generated by default as identity primary key,
    login_type text not null,
    user_name text not null,
    user_email text not null,
    web3_account text null,
    origin_data json null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now()
);

alter table public.awsl_oauth_users
    add column if not exists login_type text,
    add column if not exists user_name text,
    add column if not exists user_email text,
    add column if not exists web3_account text,
    add column if not exists origin_data json,
    add column if not exists created_at timestamp without time zone not null default now(),
    add column if not exists updated_at timestamp without time zone not null default now();

-- Repair nullable legacy rows before restoring the required constraints.
update public.awsl_oauth_users
set login_type = coalesce(nullif(login_type, ''), 'unknown'),
    user_email = coalesce(nullif(user_email, ''), 'unknown-' || id::text || '@invalid.local'),
    user_name = coalesce(nullif(user_name, ''), nullif(user_email, ''), 'oauth-user-' || id::text)
where login_type is null
   or user_email is null
   or user_name is null;

alter table public.awsl_oauth_users
    alter column login_type set not null,
    alter column user_name set not null,
    alter column user_email set not null;

create unique index if not exists awsl_oauth_users_unique_index
    on public.awsl_oauth_users (login_type, user_email);

grant all on table public.awsl_users, public.awsl_oauth_users to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;

notify pgrst, 'reload schema';
